### ISSUE TITLE
Train on kitti dataset

### ISSUE THREAD

**Issue by Gregivy** [tzaumiaan/struct2depth_test#1]
Hello!
Were you able to train the network on KITTI? Could you please provide your packages versions.

P.S. Have you faced loss inf/nan error?

**Comment by tzaumiaan** [comment]
Sorry for the delay, @Gregivy. I was a bit away from this repo recently. Yes, I've tested it with KITTI, and export it to run (see exported example https://github.com/tzaumiaan/mono_depth_assisted_tracking_by_detection)

Regarding loss inf/nan error, here are some hints:
- Direct reason: there are object masks with too small area, and when they are down-scaled 4 times (4 down sampling layers in the network) they become 0 area, which causes div-by-zero and inf. loss or NaN problem.
- Indirect reason 1: you have actually too small masks after mask generation. (This shouldn't happen with KITTI images, but if it happens just skip those too small objects, like in https://github.com/tzaumiaan/struct2depth_test/blob/acd017006bc4b1cb0f0cab7a73bada3bfa7fa9f2/cvat_anno_parser.py#L67)
- Indirect reason 2: you run it with python2 and the division is by default integer division in alignment.py. Please add "from __future__ import division" to avoid this problem.

Hope it helps. :)

**Comment by Gregivy** [comment]
Thank you @tzaumiaan! It was really helpful
