### ISSUE TITLE
Interprete Egomotion results

### ISSUE THREAD

**Issue by fangxiao-dev** [tzaumiaan/struct2depth_test#2]
Hi,

I run the algorithm and the egomotion for each frame has 1+12 values, e.g.
```
2 -0.00054003287,-9.5883326e-05,0.009118938,-0.000877027,-0.009211008,-0.0011865983 -0.0005289046,-0.00019279559,0.009116448,-0.00042416403,-0.009544066,-0.00035975612
```
I thought it should be only 1+6 values (frame index + 6 DoF). Could you provide some opinions? thank you!

**Comment by tzaumiaan** [comment]
Hi @dexter2406,

According to the original paper, https://arxiv.org/pdf/1811.06152.pdf, p.3 Motion Model, this vector contains both 6DoF motions from t-2 to t-1 and t-1 to t, and t=2 in your case. I am not the author of this paper and the model but I think to my understanding it's implemented this way. Hope this helps! :)
